---
abstract: 'A POE Filter for parsing XML with L<XML::LibXML>'
author:
  - 'Martijn van Beers  <martijn@cpan.org>'
build_requires:
  Test::More: 0
  Test::Pod: 1.00
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Filter-SAXBuilder
no_index:
  directory:
    - inc
    - t
requires:
  Class::InsideOut: 0
  Error: 0.15
  POE: 1.0
  XML::LibXML: 1.63
version: 0.03_01
