---
abstract: 'A POE Filter for parsing XML with L<XML::LibXML>'
author:
  - 'Martijn van Beers  <martijn@cpan.org>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: POE-Filter-SAXBuilder
no_index:
  directory:
    - inc
    - t
provides:
  POE::Filter::SAXBuilder:
    file: lib/POE/Filter/SAXBuilder.pm
    version: 0.04_01
  POE::Filter::SAXBuilder::Builder:
    file: lib/POE/Filter/SAXBuilder/Builder.pm
    version: 0.01
  POE::Filter::SAXBuilder::Builder::Document:
    file: lib/POE/Filter/SAXBuilder/Builder.pm
  POE::Filter::SAXBuilder::Builder::Element:
    file: lib/POE/Filter/SAXBuilder/Builder.pm
requires:
  Class::InsideOut: 0
  Error: 0.15
  POE: 1.0
  XML::LibXML: 1.63
version: 0.04_01
